// Generated by CoffeeScript 1.9.3
var Stream, generator, orderBy;

Stream = require('stream');

orderBy = require('../orderby');

generator = function(n) {
  var i, next, s;
  s = new Stream;
  i = 1;
  next = function() {
    s.emit('data', {
      name: 'name ' + i,
      value: Math.floor((i + Math.random()) * 100),
      age: Math.floor(i * 100 * Math.random() % 70),
      n_value: i,
      grade: {
        name: 'grade ' + (i % 6 + 1)
      }
    });
    i++;
    if (i === n) {
      s.emit('end');
    } else {
      process.nextTick(next);
    }
  };
  s.readable = true;
  process.nextTick(next);
  return s;
};

generator(5).pipe(orderBy([
  {
    keys: 'grade.name,value',
    reverse: true
  }, {
    getValue: function(doc) {
      return doc.age;
    },
    reverse: false
  }, 'name'
])).on('data', function(doc) {
  return console.log(doc);
}).once('end', function() {
  console.log("order by end.");
});

//# sourceMappingURL=test.js.map
